version: 0.2

phases:
    pre_build:
        commands:
          - npm install
          - npm install wait-on
    build:
        commands:
          - npm run build
reports:
    cypress_reports:
        files:
            - '*'
        file-format: JunitXml
        base-directory: 'reports'
